### ISSUE TITLE
Themes and image - Kelven

### ISSUE THREAD

**Issue by kera-cudmore** [tindyc/valentime#1]

**Comment by KelvenH** [comment]
Struggled to find a good collection of icons / images from the same collection. I've pulled some screen shots into the files below for some initial thoughts to work off. I'm not suggesting we use these images, but if there's a look / style we like I can then home in on something more suitable (or dust off my photoshop skills!);

Colors:
![colors](https://user-images.githubusercontent.com/73842369/155588413-f46ddef3-2007-4fe6-b639-781581520207.png)

Screenshots:
![Example screenshots](https://user-images.githubusercontent.com/73842369/155588701-1d71969c-7ca3-4e21-8664-4d84bbfdf8ab.png)

Category Related Images:
![Example category images](https://user-images.githubusercontent.com/73842369/155588776-c7e73e0a-8cc9-4790-8f06-6e93812869af.png)

**Comment by KelvenH** [comment]
Some initial styles which have served as inspiration for initial color schemes and imagery
