### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by kera-cudmore** [tindyc/valentime#10]
- [x] W3C validator
- [x] Javascript testing
- [x] User Stories testing
- [x] Lighthouse
- [x] bugs - solved
- [x] bugs - known

**Comment by PratimaGurav** [comment]
*Footer*
There is a gap between the footer and the end screen which is not the case on rest of the pages. 
![image](https://user-images.githubusercontent.com/85903021/155945227-bb9acd8b-300f-4782-bbff-7d08c79cd871.png)
The font color of Valentine in the footer is white on home and contact page whereas red on remaining pages.
