### ISSUE TITLE
Games Page

### ISSUE THREAD

**Issue by kera-cudmore** [tindyc/valentime#4]
Website with ideas for online games long distance relationships can play

https://www.lovingfromadistance.com/multiplayer-games/

https://www.online-tech-tips.com/fun-stuff/7-great-virtual-date-games-for-a-great-time-together/

https://www.letsroam.com/explorer/online-trivia-games-for-couples-romantic-fun/

**Comment by KelvenH** [comment]
Page completed subject to any further responsive / styling adjustments
