### ISSUE TITLE
Random Card Function

### ISSUE THREAD

**Issue by KelvenH** [tindyc/valentime#55]
Please insert the values for the Food / Movies cards - I've left 1 of the game cards in as an example. The food/movie cards are named per the current card subheadings so indicate which they relate to (i.f. FoodCook / Bake / Shake, etc). I've allowed for 3 options per card you can have more just create additional entries. Don't worry too much about the structure, i can check this when i copy across. Also, in the game example I'm not using new images at the moment so have just referenced the same image path as the front of the card - you might have new / different images for your cards.

const cardData = {
	gameSolo: [{
		title: "Club Penguin",
		url: "https://cprewritten.net/",
		image: "assets/images/controller.jpeg",
		label: "Free to play - make new friends and solve puzzles together in this frozen virtual world"
	},
	{
		title: "MiniClip",
		url: "https://www.miniclip.com/games/genre-2/multiplayer/en/",
		image: "assets/images/controller.jpeg",
		label: "Large selection of multiplayer games available on desktop and mobile. Make new friends as you team up for a challenge."
	},
	{
		title: "Best Games to Meet People Online",
		url: "https://www.esquireme.com/gaming/44920-lonely-these-are-the-best-games-to-make-friends-online",
		image: "assets/images/controller.jpeg",
		label: "Some of the best games with communities to meet new people"
	}],
 	foodCook: [{
		title: "Spicy Pesto Pasta Alla Vodka",
		url: "https://www.youtube.com/results?search_query=Spicy+Pesto+Pasta+Alla+Vodka",
		image: "",
		label: "Enjoy the flavors and taste of... authentic Italian cuisine."
	},
       {
		title: "Crispy Honey Glazed Chicken Thighs",
		url: "https://www.youtube.com/results?search_query=Crispy+Honey+Glazed+Chicken+Thighs",
		image: "",
		label: "Tweak the flavor of Chicken to suit all taste buds."
	},
        {
		title: "Roasted Salmon Nicoise",
		url: "https://www.youtube.com/results?search_query=roasted+salmon+nicoise",
		image: "",
		label: "As healthy as it could be"
	}],
       foodBake: [{
		title: "Red velvet cupcakes",
		url: "https://www.youtube.com/results?search_query=Red+velvet+cupcakes",
		image: "",
		label: "Cake is incredibly soft, moist, buttery, and topped with an easy cream cheese frosting."
	},
       {
		title: "Persian Love Cake",
		url: "https://www.youtube.com/results?search_query=Persian+Love+Cake",
		image: "",
		label: "A fragrant rose cake flavored with freshly ground cardamom and topped with crushed pistachios and rose "
	},
        {
		title: "Fudgy Brownies",
		url: "https://www.youtube.com/results?search_query=Fudgy+Brownies+",
		image: "",
		label: "These brownies are rich, fudgy in the middle and have a higher fat-to-flour ratio than cakey ones."
	}],
       foodShake: [{
		title: "Strawberry Margarita",
		url: "https://www.youtube.com/results?search_query=Strawberry+Margarita",
		image: "",
		label: "A near perfect strawberry margarita with frozen strawberries and limeade concentrate."
	},
       {
		title: "Love Potion No. 9",
		url: "https://www.youtube.com/results?search_query=love+potion+no.+9+cocktail",
		image: "",
		label: "A a sweet, spicy non-alcoholic drink."
	},
        {
		title: "Classic Mudslide",
		url: "https://www.youtube.com/results?search_query=Classic+Mudslide",
		image: "",
		label: "A delicious dessert cocktail "
	}],
 	movieSolo: [{
		title: "",
		url: "",
		image: "",
		label: ""
	},
       {
		title: "",
		url: "",
		image: "",
		label: ""
	},
        {
		title: "",
		url: "",
		image: "",
		label: ""
	}],
       movieCouples: [{
		title: "",
		url: "",
		image: "",
		label: ""
	},
       {
		title: "",
		url: "",
		image: "",
		label: ""
	},
        {
		title: "",
		url: "",
		image: "",
		label: ""
	}],
      movieFriends: [{
		title: "",
		url: "",
		image: "",
		label: ""
	},
       {
		title: "",
		url: "",
		image: "",
		label: ""
	},
        {
		title: "",
		url: "",
		image: "",
		label: ""
	}]
};

**Comment by kera-cudmore** [comment]
movieSolo: [{
title: "How to be Single",
url: "https://www.imdb.com/video/vi49721881?playlistId=tt1292566&ref_=tt_pr_ov_vi",
image: "assets/images/movies-page/how-to-be-single.webp",
label: "(2016) Comedy, Drama, Romance"
},
{
title: "Romie & Micheles High School Reunion",
url: "https://www.imdb.com/video/vi1849802265?playlistId=tt0120032&ref_=tt_pr_ov_vi",
image: "assets/images/movies-page/romy-michele",
label: "(1997) Comedy"
},
{
title: "He's Just Not That Into You",
url: "https://www.imdb.com/video/vi1239875865?playlistId=tt1001508&ref_=tt_ov_vi",
image: "assets/images/movies-page/not-into-you.webp",
label: "(2009) Comedy, Drama, Romance"
},
{
title: "Magic Mike",
url: "https://www.imdb.com/video/vi889627417?playlistId=tt1915581&ref_=tt_pr_ov_vi",
image: "assets/images/movies-page/magic-mike.webp",
label: "(2012) Comedy, Drama"
},
{
title: "La La Land",
url: "https://www.imdb.com/video/vi2514728473?playlistId=tt3783958&ref_=tt_ov_vi",
image: "assets/images/movies-page/lala-land.webp",
label: "(2016) Comedy, Drama, Musical, Romance"
}],
movieCouples: [{
title: "The Wedding Singer",
url: "https://www.imdb.com/video/vi3125853209?playlistId=tt0120888&ref_=tt_pr_ov_vi",
image: "assets/images/movies-page/wedding-singer.webp",
label: "(1998) Comedy, Romance, Music"
},
{
title: "The Notebook",
url: "https://www.imdb.com/video/vi2603746073?playlistId=tt0332280&ref_=tt_ov_vi",
image: "assets/images/movies-page/notebook.webp",
label: "(2004) Romance, Drama"
},
{
title: "Romeo & Juliet",
url: "https://www.imdb.com/video/vi58720537?playlistId=tt0117509&ref_=tt_pr_ov_vi",
image: "assets/images/movies-page/romeo-juliet",
label: "(1996) Drama, Romance"
},
{
title: "The Vow",
url: "https://www.imdb.com/video/vi236559897?playlistId=tt1606389&ref_=tt_pr_ov_vi",
image: "assets/images/movies-page/vow.webp",
label: "(2012) Drama, Romance"
},
{
title: "Sleepless in Seattle",
url: "https://www.imdb.com/video/vi727367449?playlistId=tt0108160&ref_=tt_ov_vi",
image: "assets/images/movies-page/sleepless-seattle.webp",
label: "(1993) Comedy, Drama, Romance"
}],
movieFriends: [{
title: "Girls Trip",
url: "https://www.imdb.com/video/vi3164191001?playlistId=tt3564472&ref_=tt_pr_ov_vi",
image: "assets/images/movies-page/girls-trip.webp",
label: "(2017) Comedy, Drama, Adventure"
},
{
title: "The Sweetest Thing",
url: "https://www.imdb.com/video/vi1509622041?playlistId=tt0253867&ref_=tt_pr_ov_vi",
image: "assets/images/movies-page/sweetest-thing.webp",
label: "(2002) Comedy, Romance"
},
{
title: "The Proposal",
url: "https://www.imdb.com/video/vi125895193?playlistId=tt1041829&ref_=tt_pr_ov_vi",
image: "assets/images/movies-page/proposal.webp",
label: "(2009) Comedy, Drama, Romance"
},
{
title: "My Best Friends Wedding",
url: "https://www.imdb.com/video/vi610777881?playlistId=tt0119738&ref_=tt_pr_ov_vi",
image: "assets/images/movies-page/best-friends-wedding.webp",
label: "(1997) Comedy, Drama, Romance"
},
{
title: "Someone Great",
url: "https://www.imdb.com/video/vi2772679193?playlistId=tt8075260&ref_=tt_pr_ov_vi",
image: "assets/images/movies-page/someone-great.webp",
label: "(2019) Comedy, Romance"
}]

**Comment by KelvenH** [comment]
Function incorporated which is triggered when a flash card is clicked which;
- identifies the class of the parent element to determine movie/game/food card and which of their 3 sub-categories
- pulls the respective dataset into a dictionary
- makes a random selection from the dictionary
- generates a html script populated with the dictionary values
- writes the script to the html page
